### ISSUE TITLE
Cannot copy and paste a whole SAML trace

### ISSUE THREAD

**Issue by ghalse** [magnussuther/saml-message-decoder-extension#1]
Hi

I've been using this extension for a while, and find it very useful. The new version adds some nice features, such as limiting what's captured and exporting. The former is one I've been wanting for a long time.  So I need to start by saying thanks for the good work on it :-)

However, the first time I used the new version, I discovered I could no longer do something that I previously did quite frequently: copy and paste a SAML trace. The export functionality will be useful for dealing with end users who don't understand what they're reading, but it's not so useful if I want quick access to bits of the XML to discuss with a peer. The HTML formatting was preserved in pasting it into an email, and that made it a very convenient way to demonstrate a particular problem (syntax highlighting, etc).

In the old version, I could select and scroll through the whole transaction in a single movement, allowing me to easily copy the whole thing. The way pagination works now (with arrow keys), I can't extend a selection to include more of the transaction. In both horizontal and vertical view, I can only select what's shown in the current window, which sometimes isn't even a whole request.

Is there any way to re-introduce the ability to copy-and-paste the HTML?

- Guy

**Comment by magnussuther** [comment]
Hi, sorry for breaking your workflow (and thanks for the feedback). 

The HTML formatting is preserved when copy&pasting to an email with the new version, I hope? That works for me, at least ;). There shouldn't be any differences to the previous version in this regard.

This new version uses fullpage.js to deal with the pagination, and I had some difficulties getting text selection to work at all. Fullpage.js likes to interpret that as a scrolling event. Thought I had found a way around that, but I can see the problem now: Text selection only works for the text within the viewport. (well if you use the scrollwheel you can actually select everything...). 
I guess I should just add a button in that blue titlebar for copying the XML to the clipboard. You could then remove the unnecessary XML nodes after pasting into the email, to keep only the relevant snippets. That is probably the easiest way. Thoughts?

I suppose in the previous version you could also perform a text selection through the entire list of messages in order to copy a range of related messages (that would include the titlebar text and the additional parameters too though). This is no longer possible due to the pagination. Is this a relevant use case for you? I have no idea how to make that work at the moment.

**Comment by ghalse** [comment]
The HTML formatting is preserved for the bits that I can copy - the real challenge is getting all the bits I need :). The last paragraph was indeed a use case.

The HTML syntax formatting is a nice to have; the more important thing is being able to get at the XML in a way that it can be used somewhere else (in an email, validated at https://www.samltool.com/, etc). Your idea of a button to copy just the XML would be easier/more obvious than trying to hold down a mouse button whilst using the scroll where (didn't know that worked :) - Ctrl-A does too). And it would certainly be easier than trying to get it out of the JSON export.

**Comment by magnussuther** [comment]
Understood :)

I'm working on something...

I could probably add an additional button to copy not only the currently visible SAML message but also its related message, joined via the ID <--> InResponseTo attributes. But this will only give you the request/response pair, as there's no relationship between an AuthnRequest and a LogoutRequest for example. 

A more sophisticated approach might be to add a checkbox for each message, in the titlebar, so the user can check multiple messages before clicking the button to copy. This is starting to sound a little attractive, doesn't it?

**Comment by magnussuther** [comment]
I have pushed an updated version now - might take a little while before it is available. Please try it out :)

**Comment by ghalse** [comment]
I've had a chance to play with the new version, and I quite like it :) The checkbox idea makes it easy to extract just the bits I need.

One oddity I've noticed is that when I have it set to scroll horizontally, the checkbox and "copy this message" only appear on SAMLResponses, not on SAMLRequests. I'm not sure why because if I inspect the element it's there; and it shows in the vertical scroll view, which fits within the same viewport.

**Comment by magnussuther** [comment]
Oops...
I have absolutely no idea why this happened (the absolute positioning didn't respect the boundaries of its containing div, and was rendered ~7000-ish pixels to the right), but at least I found a way around it. I just pushed another update to the webstore.
